name: account_flow
description: A simplified khatabook app for managing accounts and transactions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.0
  provider: ^6.0.5
  intl: ^0.18.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.3.7+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/1024.png"

flutter:
  uses-material-design: true